spring.jpa.hibernate:
  naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  ddl-auto: validate

management.endpoints.web.base-path: /

spring.resources.chain.cache: false

spring.mvc.dispatch-options-request: true
